trigger: 
  batch: true

pool:
  vmImage: 'vs2017-win2016'


stages:
- stage: 'Build'
  displayName: 'Build of Signaling WebService'
  pool:
    vmImage: 'vs2017-win2016'
  jobs:
  - job:
    displayName: 'Build'
  - task: PublishPipelineArtifact@1
    displayName: 'Publish Artifact: Signaling WebService'
    condition: succeeded()